# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "virtio-layer"
BBFILE_PATTERN_virtio-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_virtio-layer = "61"

BBFILES_DYNAMIC += " \
    rcar-gen3:${LAYERDIR}/dynamic-layers/rcar-gen3/*/*/*.bbappend \
    raspberrypi:${LAYERDIR}/dynamic-layers/raspberrypi/*/*/*.bbappend \
"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_virtio-layer = "1"
LAYERSERIES_COMPAT_virtio-layer = "wrynose"

LAYERDEPENDS_virtio-layer = "core filesystems-layer"
